### ISSUE TITLE
managedIdentityClientId="" required when using implicit authentication

### ISSUE THREAD

**Issue by barapz** [chriswill/serilog-sinks-azureblobstorage#121]
Hi @chriswill 

In your 4.0.0 release you changed from 
https://github.com/chriswill/serilog-sinks-azureblobstorage/blob/28d6952405621c1db778a5b87677c20397517bc6/src/Serilog.Sinks.AzureBlobStorage/LoggerConfigurationAzureBlobStorageExtensions.cs#L539
to

https://github.com/chriswill/serilog-sinks-azureblobstorage/blob/94758b450415021277b49b65b6c060c044e6cab1/src/Serilog.Sinks.AzureBlobStorage/LoggerConfigurationAzureBlobStorageExtensions.cs#L545

For us this results in having to set the attribute to "" since otherwise the call of the Method fails.

Could you change this back to  string managedIdentityClientId = null?

**Comment by chriswill** [comment]
This extension method is being used to generate a DefaultAzureCredential,  Are you doing that without specifying a managedIdentityClientId?

I'll admit I don't use this type of authentication, but I thought the clientId was generally a required item, which is why I removed the default null value.

If you generate a DefaultAzureCredential without the clientId (and it seems like you do), please let me know and I can change it back to a default null value.

**Comment by barapz** [comment]
In my setup I don't need extra credentials here since I'm using https://azure.github.io/azure-workload-identity/docs/ through which this is already satisfied.

Therefore it'd be great if you could change it back.

**Comment by chriswill** [comment]
Fixed in 4.0.3.

This required a re-ordering of the parameters in the constructor that used the managedIdentityClientId, so watch for this if you are not using named parameters.
