### ISSUE TITLE
Rolling file with UTC time

### ISSUE THREAD

**Issue by itsmaryann** [chriswill/serilog-sinks-azureblobstorage#52]
Is there a way to create the rolling file with UTC time instead of local time?
`  .WriteTo.AzureBlobStorage(connectionString, Serilog.Events.LogEventLevel.Information, null, "{yyyy}/{MM}/{dd}//hour{HH}.log")`

**Comment by chriswill** [comment]
Not at this time.  Would encourage a PR on this, although things can get challenging on *nix because it doesn't have TimeZoneInfo support.

**Comment by throck95** [comment]
@chriswill Is this as simple as updating the dtoToApply to grab the UTC DT object instead of DTO on line 43 of `BlobNameFactory.cs`? This way it's referencing an object that's already in the preferred timezone. You could even add an additional parameter in instantiation of the sink to prefer UTC and drive the determination off of that.

`defaultName = defaultName.Insert(openBraceIndex, dtoToApply.UtcDateTime.ToString(dateFormat));`

**Comment by throck95** [comment]
@chriswill I've created [PR85](https://github.com/chriswill/serilog-sinks-azureblobstorage/pull/85) that applies these changes and allows for UTC logging. I primary work on Windows and I know this works there. Not sure about Linux, though.

**Comment by chriswill** [comment]
@throck95 Thanks for your pull request.  I'll be able to review this tonight and merge if it all seems to work.

**Comment by throck95** [comment]
@itsmaryann The PR I mentioned above has been applied and released. You should be able to use the newest version and a value within the logging instantiation for using UTC or not.

**Comment by chriswill** [comment]
This issue has now been implemented.  In pull request #86 there is also a configuration option to control this behavior.
