### ISSUE TITLE
Feature Request: Azure.Storage.Blobs 12.x upgrade

### ISSUE THREAD

**Issue by JSchrepp** [chriswill/serilog-sinks-azureblobstorage#58]
Upgrading to the the latest major rev would be helpful, and knock out a couple extra issues as far as I can tell. Pre-12.x is now considered legacy (they changed package names).

Pros:
- Upgrade out of legacy dependency
- 12.x has better integration between Azure libraries, meaning Identity credential management can be integrated for free (would handle at least part of #42)
Cons:
- 12.x was built from scratch; not an easy upgrade
- Would be a breaking change for this library: some APIs here expose the old Storage SDK API.

**Comment by chriswill** [comment]
Hi @JSchrepp , thanks for the heads up about this library.  I didn't see the notes on the old lib that they had changed the name.

I looked at the library, and you're right.... fairly extensive changes.  I'll get started on it however, and when this comes out it will be a 3.x version of this library.  I just created 2.0.2, which I'll retain for people who are using the old 11.x blob library.

**Comment by danielwertheim** [comment]
@chriswill tried to reach out on Twitter regarding this. I needed the new bits and pieces as well as I wanted to use identities etc. in Azure. I started looking into updating your sink but there were, as you say, fairly extensive changes, and due to lack of time I ended up in creating a new Sink instead. Not sure if you feel bits and pieces of my Sink could be used in your project or if they instead should co-exist. Any thoughts around this?

**Comment by chriswill** [comment]
Hi @danielwertheim, sorry I didn't see your Twitter message. I'm glad that you got the basic pieces working, and I'd love to use them as a basis for updating this project.  I definitely would love to update the libraries, but I'm just slammed with other projects at the moment.  Can you give me a pointer to your repo?

**Comment by danielwertheim** [comment]
Sorry for the late answer. The code is here: https://github.com/danielwertheim/serilog-sinks-azureappendblob

**Comment by chriswill** [comment]
This has now be implemented in pull request #78 .  Published as nuget package 3.0.0
