### ISSUE TITLE
Does not log to Blob container

### ISSUE THREAD

**Issue by rdvanbuuren** [chriswill/serilog-sinks-azureblobstorage#67]
Hi,
I've got an application with plenty logging in it. But somehow I can't get this logging sink to work.
All I see is an empty Blob container 'logs' being created, but no logfiles are being pushed.

Currently, I'm using the following code that I've gotten from one of your examples:
```csharp
var connectionString = CloudStorageAccount.Parse("UseDevelopmentStorage=true");
var configuration = config.Build();
Log.Logger = new LoggerConfiguration()
  .WriteTo.Console()
  .WriteTo.AzureBlobStorage(connectionString, Serilog.Events.LogEventLevel.Information, null, "{yyyy}/{MM}/{dd}/log.txt")
  .CreateLogger();`
```
Also tried the following:
```csharp
.WriteTo.AzureBlobStorage(connectionString, Serilog.Events.LogEventLevel.Information, null, null, null, true, TimeSpan.FromSeconds(15), 10);
```
With this I'd expect some kind of logfiles every 15 seconds?

Best regard,
Rick

**Comment by AdarshGupta** [comment]
I feel your argument values (` .WriteTo.AzureBlobStorage(connectionString, Serilog.Events.LogEventLevel.Information, null, "{yyyy}/{MM}/{dd}/log.txt")`) are not as expected by the AzureBlobStorage() function (order doesn't match). You seem to call this function - https://github.com/chriswill/serilog-sinks-azureblobstorage/blob/master/src/Serilog.Sinks.AzureBlobStorage/LoggerConfigurationAzureBlobStorageExtensions.cs#L68 

Probably try named parameters - 
`
.WriteTo.AzureBlobStorage(connectionString,
                        storageContainerName: "app-logs",
                        storageFileName: "{yyyy}/{MM}/{dd}/appLogs.log",
                        writeInBatches: true,
                        period: TimeSpan.FromSeconds(15),
                        batchPostingLimit: 10)
`
And yes this should log to the file every 15 seconds unless the number of events cross 10.

**Assumptions** - 
- You are using the correct connection strings for the Azure storage account and can be accessed from your system
- The storage container name needs to be lower-case and no special symbols except dashes(-).
- If you are using the default "container name", please make sure that storage account is not linked with other services which may use it to log by default for some service activities.

**Comment by rdvanbuuren** [comment]
Just tried logging to the container with the suggestions you supplied. Unfortunately this still gives the same result.

Using `storageContainerName: "app-logs"` will create a new blob storage by that name. But files are never written to it.
Do you happen to have any other suggestions?

Running Windows Azure Storage Emulator 5.10.0.0 and Microsoft Azure Blob Storage Explorer 1.16

**Comment by AdarshGupta** [comment]
Hey @rdvanbuuren ,

I think the issue you are facing is due to the "Azure Storage Emulator". It appears to not support "Append Blobs" whereas this sink library creates append blobs to help writing logs faster. **Ref**. - check the last point in this section - https://docs.microsoft.com/en-us/azure/storage/common/storage-use-emulator#differences-for-blob-storage

I had been trying it directly with Azure cloud, so probably didn't face this issue.

There also appears to exist a **new/updated emulator** - **Azurite** (https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azurite). I haven't used it yet, but it may be worth trying it since they didn't explicitly specify it in the "Azure Cloud Vs Azurite" difference section - https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azurite#differences-between-azurite-and-azure-storage.

**Comment by rdvanbuuren** [comment]
I'm able to log now, but managed identity not working tho... Thank you for helping me!

**Comment by chriswill** [comment]
I missed the line where you said that you were working with Azure Storage Explorer.  Yes, @AdarshGupta is completely correct.  Azure Storage Explorer has no support for Append Blobs.

Regarding managed identity, that won't work until we can update the project to the latest versions of the Azure storage libraries.  It's in the plan, but it's a fairly non-trivial upgrade.
